# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden - Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
roles:
  - name: gitlab-base
    src: git+https://gitlab.com/hifis/ansible/gitlab-base-role.git
    version: master

...
