# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Set OS distribution dependent variables
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Install GitLab
  include: install.yml
  become: yes

- name: Configure GitLab
  include: configure.yml
  become: yes

...
