# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Install GitLab Dependencies.
  become: yes
  package:
    name: "{{ gitlab_dependencies_only }}"
    state: present

- name: Copy gitlab-secrets.json
  copy:
    src: "{{ gitlab_secrets_file }}"
    dest: /etc/gitlab/gitlab-secrets.json
    owner: root
    group: root
    mode: '0600'
    backup: yes
  when: gitlab_secrets_file is defined
  notify: Reconfigure GitLab

- name: Copy GitLab Configuration File.
  become: yes
  template:
    src: "{{ gitlab_configuration_file_template }}"
    dest: "{{ gitlab_configuration_file_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reconfigure GitLab

- name: Create file to prevent Gitlab to restart before migrations
  copy:
    content: ""
    dest: /etc/gitlab/skip-auto-reconfigure
    force: no
    owner: root
    group: root
    mode: '0644'
  when: gitlab_is_primary

...
