# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Install GitLab Dependencies.
  become: yes
  package:
    name: "{{ gitlab_dependencies_only }}"
    state: present

- name: Copy GitLab Configuration File.
  become: yes
  template:
    src: "{{ gitlab_configuration_file_template }}"
    dest: "{{ gitlab_configuration_file_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Reconfigure GitLab

- name: Create file to prevent Gitlab to restart before migrations
  file:
    path: /etc/gitlab/skip-auto-reconfigure
    state: present
    owner: root
    group: root
    mode: '0644'
  when: gitlab_is_primary

...
