# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: GitLab has been installed or upgraded
  become: yes
  set_fact:
    gitlab_is_upgraded: true

- name: Reconfigure Primary GitLab
  become: yes
  command: gitlab-ctl reconfigure
  register: gitlab_reconfigure
  environment:
    SKIP_POST_DEPLOYMENT_MIGRATIONS: true
  listen: GitLab has been installed or upgraded
  when: gitlab_is_primary

- name: Reconfigure Non Primary GitLab
  become: yes
  command: gitlab-ctl reconfigure
  register: gitlab_reconfigure
  listen: GitLab has been installed or upgraded
  when: not gitlab_is_primary

- name: Restart GitLab
  become: yes
  command: gitlab-ctl restart
  register: gitlab_restart

- name: Send SIGHUP to puma worker
  become: yes
  command: gitlab-ctl hup puma
  listen: GitLab has been installed or upgraded

- name: Restart sidekiq
  become: yes
  command: gitlab-ctl restart sidekiq
  listen: GitLab has been installed or upgraded

...
