# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Reconfigure Primary GitLab
  become: yes
  command: gitlab-ctl reconfigure
  register: gitlab_reconfigure
  environment:
    SKIP_POST_DEPLOYMENT_MIGRATIONS: true
  listen: GitLab has been installed or upgraded
  when: gitlab_is_primary

- name: Reconfigure Non Primary GitLab
  become: yes
  command: gitlab-ctl reconfigure
  register: gitlab_reconfigure
  listen: GitLab has been installed or upgraded
  when: not gitlab_is_primary

- name: Restart GitLab
  become: yes
  command: gitlab-ctl restart
  register: gitlab_restart

...
