# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: Reconfigure GitLab
  become: yes
  command: gitlab-ctl reconfigure
  register: gitlab_reconfigure

- name: Restart GitLab
  become: yes
  command: gitlab-ctl restart
  register: gitlab_restart

...
