# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - sudo      # for `become` privilege escalation
          - iproute2  # for gathering network facts
        state: present
        update_cache: yes
    # Provisioning freezes and GitLab "waits for redis server socket" on task "GitLab reconfigure" if file ".dockerenv" exists!
    - name: Remove file so GitLab Omnibus does not wait for redis server socket on task GitLab reconfigure.
      file:
        path: /.dockerenv
        state: absent

...
